server:
  port: 7070
spring:
  application:
    name: microservice_configServer
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bboyarchix/CarritoVentas # ruta del repositorio git
          searchPaths: config-data
          #username:
          #password:
          default-label: main
          security:
    user:
      name: root
      password: 123456
